### ISSUE TITLE
toPrepareParamsFromExecParams missing catch the error of unreached block height

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph-api#33]
If i execute a graph on a block number not reached like `99999999@sepolia`.

library will throw error as below:

<img width="630" alt="image" src="https://github.com/hyperoracle/zkgraph-lib/assets/103174898/2760e499-69c9-4f7f-8ee8-fe6850bdfee2">

How about catch it, and log a friendly error message?

**Comment by nom4dv3** [comment]
we should catch this as early as possible, e.g. when we first request the getblock, and give a err msg like "Invalid blocknum, please check the given blocknum or the chain network specified in yaml."

**Comment by murongg** [comment]
fixed in https://github.com/hyperoracle/zkgraph-api/commit/45c7bd5f62926cdbf78f410d0136e772fc7e27bf
